import type { PopupConfig, PopupType } from "./types"

export interface PopupTemplate {
  id: string
  name: string
  emoji: string
  desc: string
  type: PopupType
  build: () => PopupConfig
}

const WA_NUMBER = "254712345678"
const wa = (text: string) =>
  `https://wa.me/${WA_NUMBER}?text=${encodeURIComponent(text)}`

export const POPUP_TEMPLATES: PopupTemplate[] = [
  {
    id: "great-migration",
    name: "Great Migration Offer",
    emoji: "🔥",
    desc: "Urgency-driven Maasai Mara crossing deal",
    type: "countdown",
    build: () => ({
      name: "Great Migration Offer",
      status: "draft" as const,
      priority: 8,
      category: "Seasonal",
      notes: "Show during July–October migration season",
      type: "countdown" as const,
      template: "great-migration",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "🔥 Witness the Great Migration",
        subtitle: "Limited crossings at the Mara River",
        description:
          "Book now and watch over 1.5 million wildebeest thunder across the Mara River. River crossings peak in the next 3 weeks — don't miss it!",
        emoji: true,
        badges: ["Best Price Guarantee", "Expert Guides"],
        countdownEndsAt: "",
        promoCode: "MIGRATION10",
        priceBefore: "$2,400",
        priceNow: "$2,160",
      },
      ctas: [
        {
          id: "c1", label: "Book Safari", url: "/contact", newTab: false,
          bgColor: "#f59e0b", textColor: "#ffffff", hoverAnimation: "pulse" as const, icon: "🎯", type: "url",
        },
        {
          id: "c2", label: "Chat on WhatsApp", url: wa("Hi! I'm interested in the Great Migration safari"), newTab: true,
          bgColor: "#25d366", textColor: "#ffffff", hoverAnimation: "grow" as const, icon: "💬", type: "whatsapp",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 0, minTimeSeconds: 0, exitIntent: false, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_per_day", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: true, suppressAfterBooking: true, suppressAfterWhatsApp: true },
      advanced: { trigger: "delay", delaySeconds: 6, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: true, remainingSeats: 12, peopleViewing: true, recentlyBooked: true, liveFeed: false, trustBadges: ["✅ Trusted Local Operator", "⭐ 4.9 Google Rating"], googleReviews: 4.9, tripadvisorRating: 5, securePayment: true, moneyBack: true, awardBadges: ["🏆 Award-Winning Safaris"], customerPhotos: true, videoTestimonials: false },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 2160,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "diani",
    name: "Diani Beach Holiday",
    emoji: "🌴",
    desc: "Relaxation beach getaway with palm imagery",
    type: "hero",
    build: () => ({
      name: "Diani Beach Holiday",
      status: "draft" as const,
      priority: 6,
      category: "Destinations",
      notes: "Target beach-lovers and honeymooners",
      type: "hero" as const,
      template: "diani",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "🌴 Diani Beach Escape",
        subtitle: "7 days of white sand & turquoise water",
        description:
          "Stay at award-winning beach resorts with free breakfast, daily excursions and sunset dhow cruises included.",
        emoji: true,
        badges: ["All Inclusive", "Free Airport Pickup"],
        countdownEndsAt: "",
        promoCode: "BEACH20",
        priceBefore: "$1,800",
        priceNow: "$1,440",
      },
      ctas: [
        {
          id: "c1", label: "View Packages", url: "/beach-holidays", newTab: false,
          bgColor: "#0ea5e9", textColor: "#ffffff", hoverAnimation: "grow" as const, icon: "🗓️", type: "url",
        },
        {
          id: "c2", label: "WhatsApp Us", url: wa("Hi! I'd like more info on the Diani Beach holiday"), newTab: true,
          bgColor: "#25d366", textColor: "#ffffff", hoverAnimation: "pulse" as const, icon: "💬", type: "whatsapp",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 1, minTimeSeconds: 0, exitIntent: false, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_ever", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: false, suppressAfterBooking: false, suppressAfterWhatsApp: false },
      advanced: { trigger: "delay", delaySeconds: 8, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: false, remainingSeats: null, peopleViewing: false, recentlyBooked: false, liveFeed: false, trustBadges: ["✅ Trusted Local Operator"], googleReviews: null, tripadvisorRating: null, securePayment: true, moneyBack: false, awardBadges: [], customerPhotos: true, videoTestimonials: false },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 1440,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "masai-mara",
    name: "Maasai Mara Safari",
    emoji: "🦁",
    desc: "Big-cat adventure with scarcity",
    type: "seats",
    build: () => ({
      name: "Maasai Mara Safari",
      status: "draft" as const,
      priority: 7,
      category: "Destinations",
      notes: "",
      type: "seats" as const,
      template: "masai-mara",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "🦁 Maasai Mara Safari",
        subtitle: "Big 5 guaranteed or your money back",
        description:
          "Join our legendary 5-day Mara expedition with professional safari guides, luxury tented camps and daily game drives.",
        emoji: true,
        badges: ["Big 5 Guarantee", "Small Groups"],
        countdownEndsAt: "",
        promoCode: "MARASAVE",
        priceBefore: "$2,150",
        priceNow: "$1,935",
      },
      ctas: [
        {
          id: "c1", label: "Book Safari", url: "/kenya-tours", newTab: false,
          bgColor: "#f59e0b", textColor: "#ffffff", hoverAnimation: "grow" as const, icon: "🎯", type: "url",
        },
        {
          id: "c2", label: "Chat on WhatsApp", url: wa("Hi! I'm interested in the Maasai Mara safari"), newTab: true,
          bgColor: "#25d366", textColor: "#ffffff", hoverAnimation: "grow" as const, icon: "💬", type: "whatsapp",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 2, minTimeSeconds: 15, exitIntent: false, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_per_week", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: true, suppressAfterBooking: true, suppressAfterWhatsApp: true },
      advanced: { trigger: "delay", delaySeconds: 10, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: true, remainingSeats: 8, peopleViewing: true, recentlyBooked: true, liveFeed: false, trustBadges: ["✅ Trusted Local Operator", "🌍 5,000+ Happy Travellers"], googleReviews: 4.9, tripadvisorRating: 5, securePayment: true, moneyBack: true, awardBadges: ["🥇 Best Safari Operator 2025"], customerPhotos: true, videoTestimonials: true },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 1935,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "honeymoon",
    name: "Honeymoon Packages",
    emoji: "💍",
    desc: "Romantic escapes with luxury imagery",
    type: "corner",
    build: () => ({
      name: "Honeymoon Packages",
      status: "draft" as const,
      priority: 5,
      category: "Romance",
      notes: "",
      type: "corner" as const,
      template: "honeymoon",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "💍 Honeymoon in Paradise",
        subtitle: "Romantic safari + beach combo",
        description:
          "Sunrise hot air balloon over the Mara, champagne dinners on the beach. Free honeymoon upgrade when you book this month.",
        emoji: true,
        badges: ["Free Honeymoon Upgrade", "5-Star Lodges"],
        countdownEndsAt: "",
        promoCode: "HONEYMOON",
        priceBefore: "$3,200",
        priceNow: "$2,880",
      },
      ctas: [
        {
          id: "c1", label: "View Packages", url: "/honeymoon-packages", newTab: false,
          bgColor: "#ec4899", textColor: "#ffffff", hoverAnimation: "pulse" as const, icon: "💍", type: "url",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 0, minTimeSeconds: 0, exitIntent: true, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_ever", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: false, suppressAfterBooking: false, suppressAfterWhatsApp: false },
      advanced: { trigger: "exit", delaySeconds: 0, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: false, remainingSeats: null, peopleViewing: false, recentlyBooked: false, liveFeed: false, trustBadges: ["🔒 Secure Booking", "💵 Best Price Guarantee"], googleReviews: null, tripadvisorRating: null, securePayment: true, moneyBack: false, awardBadges: ["🏆 Award-Winning Safaris"], customerPhotos: true, videoTestimonials: false },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 2880,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "amboseli",
    name: "Amboseli Special",
    emoji: "🐘",
    desc: "Elephants & Kilimanjaro backdrop",
    type: "flash",
    build: () => ({
      name: "Amboseli Special",
      status: "draft" as const,
      priority: 6,
      category: "Destinations",
      notes: "Flash sale style urgency",
      type: "flash" as const,
      template: "amboseli",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "🐘 Amboseli Special",
        subtitle: "Elephants beneath Kilimanjaro",
        description:
          "This week only: 25% off our Amboseli packages. Herds of elephants, views of Mt. Kilimanjaro, and luxury safari tents.",
        emoji: true,
        badges: ["25% OFF", "This Week Only"],
        countdownEndsAt: "",
        promoCode: "AMBOSELI25",
        priceBefore: "$1,950",
        priceNow: "$1,462",
      },
      ctas: [
        {
          id: "c1", label: "Claim Offer", url: "/contact", newTab: false,
          bgColor: "#ef4444", textColor: "#ffffff", hoverAnimation: "shake" as const, icon: "⚡", type: "url",
        },
        {
          id: "c2", label: "Chat on WhatsApp", url: wa("Hi! I'd like to claim the Amboseli special"), newTab: true,
          bgColor: "#25d366", textColor: "#ffffff", hoverAnimation: "grow" as const, icon: "💬", type: "whatsapp",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 0, minTimeSeconds: 0, exitIntent: false, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_per_day", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: true, suppressAfterBooking: true, suppressAfterWhatsApp: true },
      advanced: { trigger: "delay", delaySeconds: 5, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: true, remainingSeats: 15, peopleViewing: true, recentlyBooked: true, liveFeed: false, trustBadges: ["✅ Trusted Local Operator"], googleReviews: null, tripadvisorRating: null, securePayment: true, moneyBack: false, awardBadges: [], customerPhotos: true, videoTestimonials: false },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 1462,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "zanzibar",
    name: "Zanzibar Escape",
    emoji: "🏖️",
    desc: "Island paradise with spice tour add-ons",
    type: "fullscreen",
    build: () => ({
      name: "Zanzibar Escape",
      status: "draft" as const,
      priority: 6,
      category: "Destinations",
      notes: "",
      type: "fullscreen" as const,
      template: "zanzibar",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "🏖️ Zanzibar Escape",
        subtitle: "Stone Town, spice farms & powder beaches",
        description:
          "Fly to paradise: 5 nights in a beachfront villa, spice tour, blue safari and private dhow sunset cruise.",
        emoji: true,
        badges: ["Flights Included", "Beachfront Villa"],
        countdownEndsAt: "",
        promoCode: "ZANZIBAR",
        priceBefore: "$2,650",
        priceNow: "$2,385",
      },
      ctas: [
        {
          id: "c1", label: "View Packages", url: "/holiday-packages", newTab: false,
          bgColor: "#0d9488", textColor: "#ffffff", hoverAnimation: "grow" as const, icon: "🗓️", type: "url",
        },
        {
          id: "c2", label: "Download Brochure", url: "/brochure.pdf", newTab: true,
          bgColor: "#475569", textColor: "#ffffff", hoverAnimation: "none" as const, icon: "📄", type: "download",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 0, minTimeSeconds: 0, exitIntent: false, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_ever", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: false, suppressAfterBooking: false, suppressAfterWhatsApp: false },
      advanced: { trigger: "delay", delaySeconds: 12, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: false, remainingSeats: null, peopleViewing: false, recentlyBooked: false, liveFeed: false, trustBadges: ["✅ Trusted Local Operator", "🌍 5,000+ Happy Travellers"], googleReviews: null, tripadvisorRating: null, securePayment: true, moneyBack: false, awardBadges: [], customerPhotos: true, videoTestimonials: false },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 2385,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "family",
    name: "Family Holiday",
    emoji: "👨‍👩‍👧",
    desc: "Kids-stay-free family packages",
    type: "sticky",
    build: () => ({
      name: "Family Holiday",
      status: "draft" as const,
      priority: 5,
      category: "Family",
      notes: "Sticky bar — gentle, non-intrusive",
      type: "sticky" as const,
      template: "family",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "👨‍👩‍👧 Family Holiday",
        subtitle: "Kids under 12 stay free",
        description:
          "Family-friendly lodges, junior ranger programs and big 5 safaris the whole family will love.",
        emoji: true,
        badges: ["Kids Free", "Family Rooms"],
        countdownEndsAt: "",
        promoCode: "FAMILYFREE",
        priceBefore: "$2,900",
        priceNow: "$2,610",
      },
      ctas: [
        {
          id: "c1", label: "View Packages", url: "/holiday-packages", newTab: false,
          bgColor: "#22c55e", textColor: "#ffffff", hoverAnimation: "grow" as const, icon: "🚀", type: "url",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 0, minTimeSeconds: 0, exitIntent: false, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_per_day", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: false, suppressAfterBooking: false, suppressAfterWhatsApp: false },
      advanced: { trigger: "delay", delaySeconds: 15, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: false, remainingSeats: null, peopleViewing: false, recentlyBooked: false, liveFeed: false, trustBadges: ["✅ Trusted Local Operator"], googleReviews: null, tripadvisorRating: null, securePayment: true, moneyBack: false, awardBadges: [], customerPhotos: true, videoTestimonials: false },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 2610,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "early-bird",
    name: "Early Bird Discount",
    emoji: "🛫",
    desc: "Book 90 days ahead, save 15%",
    type: "modal",
    build: () => ({
      name: "Early Bird Discount",
      status: "draft" as const,
      priority: 6,
      category: "Offers",
      notes: "",
      type: "modal" as const,
      template: "early-bird",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "🛫 Early Bird Discount",
        subtitle: "Book 90+ days ahead & save 15%",
        description:
          "Planning ahead pays off. Reserve your 2026 safari now and lock in today's prices with flexible cancellation.",
        emoji: true,
        badges: ["Flexible Cancellation", "Locked Prices"],
        countdownEndsAt: "",
        promoCode: "EARLY15",
        priceBefore: "",
        priceNow: "Save 15%",
      },
      ctas: [
        {
          id: "c1", label: "Get My Quote", url: "/contact", newTab: false,
          bgColor: "#8b5cf6", textColor: "#ffffff", hoverAnimation: "pulse" as const, icon: "🚀", type: "url",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 0, minTimeSeconds: 0, exitIntent: false, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_ever", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: true, suppressAfterBooking: true, suppressAfterWhatsApp: false },
      advanced: { trigger: "delay", delaySeconds: 7, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: false, remainingSeats: null, peopleViewing: false, recentlyBooked: false, liveFeed: false, trustBadges: ["🔒 Secure Booking", "💵 Best Price Guarantee"], googleReviews: null, tripadvisorRating: null, securePayment: true, moneyBack: true, awardBadges: [], customerPhotos: false, videoTestimonials: false },
      leadForm: { enabled: true, fields: ["name", "email", "phone", "travel_date", "destination"], submitLabel: "Get My Free Quote", successMessage: "Thanks! We'll send your early-bird quote within 24 hours.", emailRequired: true },
      conversionValue: 1800,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "last-minute",
    name: "Last Minute Deals",
    emoji: "⚡",
    desc: "Departures within 14 days",
    type: "flash",
    build: () => ({
      name: "Last Minute Deals",
      status: "draft" as const,
      priority: 9,
      category: "Offers",
      notes: "Highest priority — show first",
      type: "flash" as const,
      template: "last-minute",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "⚡ Last Minute Deals",
        subtitle: "Departures within 14 days",
        description:
          "Safari departures leaving this month at up to 40% off. Availability won't last — grab your spot today!",
        emoji: true,
        badges: ["Up to 40% OFF", "Departing Soon"],
        countdownEndsAt: "",
        promoCode: "LASTMIN40",
        priceBefore: "$2,000",
        priceNow: "$1,200",
      },
      ctas: [
        {
          id: "c1", label: "Claim Offer", url: "/deals", newTab: false,
          bgColor: "#f97316", textColor: "#ffffff", hoverAnimation: "shake" as const, icon: "🔥", type: "url",
        },
        {
          id: "c2", label: "WhatsApp", url: wa("Hi! Any last minute safari deals available?"), newTab: true,
          bgColor: "#25d366", textColor: "#ffffff", hoverAnimation: "pulse" as const, icon: "💬", type: "whatsapp",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 0, minTimeSeconds: 0, exitIntent: true, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_per_day", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: true, suppressAfterBooking: true, suppressAfterWhatsApp: true },
      advanced: { trigger: "delay", delaySeconds: 4, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: true, remainingSeats: 6, peopleViewing: true, recentlyBooked: true, liveFeed: true, trustBadges: ["✅ Trusted Local Operator", "🌍 5,000+ Happy Travellers"], googleReviews: null, tripadvisorRating: null, securePayment: true, moneyBack: true, awardBadges: [], customerPhotos: true, videoTestimonials: false },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 1200,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "christmas",
    name: "Christmas Safari",
    emoji: "🎉",
    desc: "Festive season bookings",
    type: "countdown",
    build: () => ({
      name: "Christmas Safari",
      status: "draft" as const,
      priority: 7,
      category: "Seasonal",
      notes: "Run Dec 1 – Jan 5",
      type: "countdown" as const,
      template: "christmas",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "",
        title: "🎉 Christmas Safari",
        subtitle: "Celebrate the holidays on safari",
        description:
          "Christmas dinner under the stars, festive game drives and family lodges with holiday activities for the kids.",
        emoji: true,
        badges: ["Festive Special", "Family Friendly"],
        countdownEndsAt: "",
        promoCode: "XMAS10",
        priceBefore: "",
        priceNow: "10% Off",
      },
      ctas: [
        {
          id: "c1", label: "Book Safari", url: "/contact", newTab: false,
          bgColor: "#dc2626", textColor: "#ffffff", hoverAnimation: "pulse" as const, icon: "🎁", type: "url",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 0, minTimeSeconds: 0, exitIntent: false, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_per_week", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: true, suppressAfterBooking: true, suppressAfterWhatsApp: false },
      advanced: { trigger: "delay", delaySeconds: 9, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: true, remainingSeats: 20, peopleViewing: true, recentlyBooked: true, liveFeed: false, trustBadges: ["✅ Trusted Local Operator"], googleReviews: null, tripadvisorRating: null, securePayment: true, moneyBack: false, awardBadges: [], customerPhotos: true, videoTestimonials: false },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 2200,
      startDate: null,
      endDate: null,
    }),
  },
  {
    id: "new-year",
    name: "New Year Safari",
    emoji: "🎆",
    desc: "Ring in the New Year on safari",
    type: "video",
    build: () => ({
      name: "New Year Safari",
      status: "draft" as const,
      priority: 7,
      category: "Seasonal",
      notes: "Showcase video of safari highlights",
      type: "video" as const,
      template: "new-year",
      content: {
        heroImage: "",
        backgroundImage: "",
        video: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        title: "🎆 New Year Safari",
        subtitle: "Ring in 2026 under the African sky",
        description:
          "Celebrate New Year with a champagne toast at sunset, bonfire parties and a midnight game drive under the stars.",
        emoji: true,
        badges: ["Limited NYE Spots"],
        countdownEndsAt: "",
        promoCode: "NYE2026",
        priceBefore: "",
        priceNow: "Early Bird 15%",
      },
      ctas: [
        {
          id: "c1", label: "Book Safari", url: "/contact", newTab: false,
          bgColor: "#7c3aed", textColor: "#ffffff", hoverAnimation: "grow" as const, icon: "🎆", type: "url",
        },
      ],
      targeting: {
        visitorType: "all", minPagesVisited: 0, minTimeSeconds: 0, exitIntent: false, scrollDepth: 0,
        pages: "all", customPages: [], devices: [], countries: [], languages: [], trafficSources: [], utmCampaign: "",
      },
      frequency: { show: "once_per_week", everyXDays: 7, maxPerSession: 1, suppressAfterConversion: true, suppressAfterBooking: true, suppressAfterWhatsApp: false },
      advanced: { trigger: "delay", delaySeconds: 8, inactivitySeconds: 15, businessHoursOnly: false, businessHoursStart: "08:00", businessHoursEnd: "22:00", weekendOnly: false, dateWindowStart: null, dateWindowEnd: null },
      conversion: { countdown: true, remainingSeats: 10, peopleViewing: true, recentlyBooked: true, liveFeed: false, trustBadges: ["✅ Trusted Local Operator"], googleReviews: null, tripadvisorRating: null, securePayment: true, moneyBack: false, awardBadges: [], customerPhotos: true, videoTestimonials: true },
      leadForm: { enabled: false, fields: ["name", "email", "phone"], submitLabel: "Get My Free Quote", successMessage: "Thank you! We'll get back to you within 24 hours.", emailRequired: true },
      conversionValue: 2500,
      startDate: null,
      endDate: null,
    }),
  },
]

export function getTemplate(id: string): PopupConfig | null {
  const t = POPUP_TEMPLATES.find((x) => x.id === id)
  return t ? t.build() : null
}

export const TEMPLATE_EMOJIS: Record<string, string> = Object.fromEntries(
  POPUP_TEMPLATES.map((t) => [t.id, t.emoji])
)
